DoctorsOffice/Models/Patient.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DoctorsOffice.Models
{
  public class Patient
  {
    public Patient()
    {
      this.Doctors = new HashSet<DoctorPatient>();
    }

    public int PatientId { get; set; }
    public string Name { get; set; }
    [DisplayFormat(DataFormatString = "{0:dd MM yyy}")]
    public System.DateTime Birthday { get; set; }
    public ICollection<DoctorPatient> Doctors { get; }
  }
}

DoctorsOffice/Controllers/DoctorsController.cs
using DoctorsOffice.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace DoctorsOffice.Controllers
{
  public class DoctorsController : Controller
  {
    private readonly DoctorsOfficeContext _db;

    public DoctorsController(DoctorsOfficeContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Doctor> model = _db.Doctors.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.SpecialtyId = new SelectList(_db.Specialties, "SpecialtyId", "Name");
      return View();
    }


    [HttpPost]
    public ActionResult Create(Doctor doctor)
    {
      _db.Doctors.Add(doctor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisDoctor = _db.Doctors
        .Include(doctor => doctor.Patients)
        .ThenInclude(join => join.Patient)
        .FirstOrDefault(doctor => doctor.DoctorId == id);
        return View(thisDoctor);
    }

    public ActionResult Edit(int id)
    {
      var thisDoctor = _db.Doctors.FirstOrDefault(Doctor => Doctor.DoctorId == id);
      return View(thisDoctor);
    }

    [HttpPost]
    public ActionResult Edit(Doctor doctor)
    {
      _db.Entry(doctor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddPatient(int id)
    {
      var thisDoctor = _db.Doctors.FirstOrDefault(doctors => doctors.DoctorId == id);
      ViewBag.PatientId = new SelectList(_db.Patients, "PatientId", "Name");
      return View(thisDoctor);
    }

    [HttpPost]
    public ActionResult AddPatient(Doctor doctor, int PatientId)
    {
      if(PatientId != 0 && !_db.DoctorPatient.Any(x => x.PatientId == PatientId && x.DoctorId == doctor.DoctorId))
      {
        _db.DoctorPatient.Add(new DoctorPatient() { PatientId = PatientId, DoctorId = doctor.DoctorId});
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = doctor.DoctorId});
    }

    public ActionResult AddSpecialty(int id)
    {
      var thisDoctor = _db.Doctors.FirstOrDefault(doctors => doctors.DoctorId == id);
      ViewBag.SpecialtyId = new SelectList(_db.Specialties, "SpecialtyId", "Name");
      return View(thisDoctor);
    }

    [HttpPost]
    public ActionResult AddSpecialty(Doctor doctor, int SpecialtyId)
    {
      if(SpecialtyId != 0 && !_db.DoctorSpecialty.Any(x => x.SpecialtyId == SpecialtyId  x.DoctorId == doctor.DoctorId))
      {
        _db.DoctorSpecialty.Add(new DoctorSpecialty() { SpecialtyId = SpecialtyId, DoctorId = doctor.DoctorId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = doctor.DoctorId });
    }

    public ActionResult Delete(int id)
    {
      var thisDoctor = _db.Doctors.FirstOrDefault(doctor => doctor.DoctorId == id);
      return View(thisDoctor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisDoctor = _db.Doctors.FirstOrDefault(doctor => doctor.DoctorId == id);
      _db.Doctors.Remove(thisDoctor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult RemovePatient(int joinId)
    {
      var joinEntry = _db.DoctorPatient.FirstOrDefault(entry => entry.DoctorPatientId == joinId);
      _db.DoctorPatient.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = joinEntry.DoctorId});
    }
  }
}

DoctorsOffice/Controllers/PatientsController.cs
using DoctorsOffice.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace DoctorsOffice.Controllers
{
  public class PatientsController : Controller
  {
    private readonly DoctorsOfficeContext _db;

    public PatientsController(DoctorsOfficeContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Patients.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Patient patient, int DoctorId)
    {
      _db.Patients.Add(patient);
      if(DoctorId != 0)
      {
        _db.DoctorPatient.Add(new DoctorPatient() {DoctorId = DoctorId, PatientId = patient.PatientId});
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisPatient = _db.Patients
      .Include(patient => patient.Doctors)
      .ThenInclude(join => join.Doctor)
      .FirstOrDefault(patient => patient.PatientId == id);
      return View(thisPatient);
    }

    public ActionResult Edit(int id)
    {
      var thisPatient = _db.Patients.FirstOrDefault(patients => patients.PatientId == id);
      return View(thisPatient);
    }

    [HttpPost]
    public ActionResult Edit(Patient patient)
    {
      _db.Entry(patient).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = patient.PatientId});
    }

    public ActionResult AddDoctor(int id)
    {
      var thisPatient = _db.Patients.FirstOrDefault(patients => patients.PatientId == id);
      ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "Name");
      return View(thisPatient);
    }

    [HttpPost]
    public ActionResult AddDoctor(Patient patient, int DoctorId)
    {
      if(DoctorId != 0 && !_db.DoctorPatient.Any(x => x.DoctorId == DoctorId && x.PatientId == patient.PatientId))
      {
        _db.DoctorPatient.Add(new DoctorPatient() { DoctorId = DoctorId, PatientId = patient.PatientId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = patient.PatientId});
    }

    public ActionResult Delete(int id)
    {
      var thisPatient = _db.Patients.FirstOrDefault(patients => patients.PatientId == id);
      return View(thisPatient);
    }

    [HttpPost]
    public ActionResult RemoveDoctor(int joinId)
    {
      var joinEntry = _db.DoctorPatient.FirstOrDefault(entry => entry.DoctorPatientId == joinId);
      _db.DoctorPatient.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = joinEntry.PatientId });
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisPatient = _db.Patients.FirstOrDefault(patients => patients.PatientId == id);
      _db.Patients.Remove(thisPatient);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

DoctorsOffice/Views/Patients/AddDoctor.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Patient

<h4>Add a New Doctor</h4>

@using (Html.BeginForm())
{

  @Html.HiddenFor(model => model.PatientId)

  @Html.Label("Select Doctor")
  @Html.DropDownList("DoctorId")

  <input type="submit" value="Add New Doctor" class="btn btn-default" />
}

<p>@Html.ActionLink("Back to patient details", "Details", new { id = Model.PatientId })</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

DoctorsOffice/Views/Patients/Create.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Patient

<h1>Add a new patient</h1>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.Birthday)
  @Html.TextBox("Birthday", null, new { type="date"})

  @Html.Label("Select doctor")
  @Html.DropDownList("DoctorId")

  <input type="submit" value="Add new patient"/>
}

<p>@Html.ActionLink("View all patients", "Index")</p>

DoctorsOffice/Views/Patients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Patient

<h2>Are you sure you want to delete this patient?</h2>

@Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to patient list", "Index")
@Html.ActionLink("Home", "Index", "Home")

DoctorsOffice/Views/Patients/Details.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Patient

<h2>Patient Details:</h2>
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>


<h3>Date of Birth: @Html.DisplayFor(model => model.Birthday)</h3>

<h2>This patient sees the following doctors:</h2>

@if(@Model.Doctors.Count == 0)
{
  <p>This patient doesn't have any doctors yet.</p>
}
else
{
  <ul>
  @foreach(var join in Model.Doctors)
  {
    <li>@Html.ActionLink($"{join.Doctor.Name}, {join.Doctor.Specialty}", "Details", "Doctors", new { id = join.DoctorId})</li>
    @using (Html.BeginForm("RemoveDoctor", "Patients"))
    {
      @Html.Hidden("joinId", @join.DoctorPatientId)
      <input type="submit" value="Remove Doctor"/>
    }
  }
  </ul>
}

<p>@Html.ActionLink("Home", "Index", "Home")</p>
<p>@Html.ActionLink("Delete Patient", "Delete", new { id = Model.PatientId})</p>
<p>@Html.ActionLink("See all patients", "Index")</p>
<p>@Html.ActionLink("Edit Patient", "Edit", new { id = Model.PatientId})</p>
<p>@Html.ActionLink("Add doctor", "AddDoctor", new { id = Model.PatientId})</p>

DoctorsOffice/Views/Patients/Edit.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Patient

<h1>Edit Patient Info</h1>

<h2>Patient: @Html.DisplayFor(model => model.Name)</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.PatientId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.Birthday)
  @Html.TextBox("Birthday", null, new { type="date"})

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("View All Patients", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

DoctorsOffice/Views/Patients/Index.cshtml
@{
  Layout = "_Layout";
}

@using DoctorsOffice.Models
@model List<DoctorsOffice.Models.Patient>;

<h1>Patients</h1>

@if(@Model.Count == 0)
{
  <h3>There are no patients.</h3>
}
else
{
  <ul>
    @foreach (Patient patient in Model)
    {
      <li>@Html.ActionLink($"{patient.Name}", "Details", new { id = patient.PatientId})</li>
    }
  </ul>
}

<p>@Html.ActionLink("Add a new patient", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>